config/routes.rb
Rails.application.routes.draw do
  root 'login#new'
  get 'signup' => 'signup#new'
  post 'signup' => 'signup#create'

  get 'login' => 'login#new'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'

  get 'tasks' => 'tasks#index'
  post 'tasks/new' => 'tasks#create', as: 'new_task'
  post 'tasks/update' => 'tasks#batch_update', as: 'update_tasks'
  get 'tasks/:id/edit' => 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id/edit' => 'tasks#update', as: false
  delete 'tasks/:id' => 'tasks#destroy', as: 'remove_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :user

  def completed?
    completed_at?
  end

  def status
    if completed_at?
      'complete'
    else
      'pending'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /
    \A
    [a-z0-9] + ([._][a-z0-9]+)*
    (\+[ˆ@]+)?
    @
    [a-z0-9] + ([._][a-z0-9]+)*
    \.[a-z]{2,4}
    \z
  /xi

  has_secure_password

  validates_presence_of :name, :email
  validates_format_of :email, with: EMAIL_FORMAT
  validates_uniqueness_of :email

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  before_action :set_locale

  def default_url_options(options={})
    options.merge(locale: I18n.locale)
  end

  private

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :logged_in?, :current_user
  end

  private

  def redirect_logger_user
    redirect_to tasks_path if logged_in?
  end
  
  def require_logged_user
    redirect_to login_path,
      alert: t('flash.must_be_logged_in') unless logged_in?
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :redirect_logger_user, except: %w[destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      reset_session
      session[:user_id] = user.id

      redirect_to tasks_path
    else
      redirect_to login_path, alert: t('flash.login.create.alert')
    end
  end

  def destroy
    reset_session
    redirect_to login_path,
      notice: t('flash.login.destroy.notice')
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: t('flash.signup.create.notice')
    else
      render :new
    end
  end

  private

  def user_params
    params
    .require(:user)
    .permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_logged_user

  def index
    @task = Task.new
    @tasks = current_user.tasks.order('completed_at')
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path,
        notice: t('flash.tasks.create.notice')
      else
        render :new
      end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path,
        notice: t('flash.tasks.update.notice')
      else
        render :new
      end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy!

    redirect_to tasks_path,
      notice: t('flash.tasks.destroy.notice')
  end

  def batch_update
    Task.transaction do
      current_user.tasks.where(id: params[:task_ids], completed_at: nil)
      .update_all(completed_at: Time.current)

      current_user.tasks.where.not(id: params[:task_ids])
      .update_all(completed_at: nil)

      redirect_to tasks_path,
        notice: "Atualizou todos!"
    end
  end

  private

  def task_params
    params
    .require(:task)
    .permit(:title, :task_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors_message.html.erb
<% if record.errors.any? %>
  <div class="error-messages">
    <p>
      <%= t('errors.form_error_message')  %>
    </p>
    <ul>
      <% for message in record.errors.full_messages %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <p class="message <%= type %>">
    <%= message %>
  </p>
<% end %>

app/views/application/_main_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag 'tasks.png'  %>
  <% end %>

  <nav>
    <% if logged_in? %>
      <%= t('greeting', name: current_user.name) %>
      <%= button_to t('menu.logout'), logout_path, method: 'delete' %>
    <% else %>
      <%= link_to t('menu.signup'), signup_path %>
      <%= link_to t('menu.login') , root_path %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <%= render 'main_header' %>
      <%= render 'flash_messages' %>
      <%= yield %>
    </div>
  </body>
  <footer>
    <p class="language">
      <%= t('select_locale') %>
      <%= link_to 'English', '/?locale=en' %>
      <%= link_to 'Português', '/?locale=pt-BR' %>
    </p>
  </footer>
</html>

app/views/login/new.html.erb
<h2><%= t('titles.login') %></h2>

<%= form_tag login_path do %>
  <div>
    <%= label_tag :email, t('labels.user.email') %>
    <%= email_field_tag :email %>
  </div>

  <div>
    <%= label_tag :password, t('labels.user.password') %>
    <%= password_field_tag :password %>
  </div>

<div>
  <%= submit_tag t('helpers.submit.login'), class: 'button' %>
</div>
<% end %>

app/views/signup/new.html.erb
<h2><%= t('titles.signup') %></h2>
<%= render 'errors_message', record: @user %>

<%= form_for @user, url: signup_path do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit t('helpers.submit.signup'), class: 'button' %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for task, url: url do |f| %>
  <div class="task-form no-separator">
    <%= f.label :title, t('labels.task.title') %>
    <%= f.text_field :title %>
    <%= f.submit class: 'button' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li class="<%= task.status %>">
  <%= check_box_tag 'task_ids[]', task.id, task.completed?, id: dom_id(task) %>
  <label for="<%= dom_id(task) %>"><%= task.title %></label>

  <span class="actions">
    <%= link_to t('helpers.actions.tasks.edit'), edit_task_path(task) %>
    <%= link_to t('helpers.actions.tasks.delete'), remove_task_path(task), method: 'delete' %>
  </span>
</li>

app/views/tasks/edit.html.erb
<%= render 'errors_message', record: @task %>
<%= render 'form', task: @task, url: edit_task_path(@task) %>

app/views/tasks/index.html.erb
<%= render 'form', task: @task, url: new_task_path %>

<%= form_tag update_tasks_path do %>
  <ul class="tasks">
    <%= render @tasks %>
  </ul>

  <div>
    <%= submit_tag t('helpers.submit.update_all'), class: 'button' %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<%= render 'errors_message', record: @task %>
<%= render 'form', task: @task, url: new_task_path %>